### ISSUE TITLE
Change "Definition" to "Definitions" 

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/open-organization.github.io#20]
global nav link should be plural, with a landing page linking out to:

- [x] Open Org Definition
- [x] Open Org Maturity Model
- [x] Open Leadership Definition

**Comment by semioticrobotic** [comment]
I've begun working on this issue in a [new branch](https://github.com/open-organization/open-organization.github.io/tree/def-page) called ``def-page``. Others welcome to join me there.

**Comment by LauraHilliger** [comment]
crap, I sent a PR: https://github.com/open-organization/open-organization.github.io/pulls

**Comment by semioticrobotic** [comment]
I actually think we'll need to write a high-level description of the Open Organization Definition in order to complete this work. I logged that [in the definition repository](https://github.com/open-organization/open-org-definition/issues/27) thinking we'd get to it later, but I think we'll actually need that text to assist us with this new landing page.

**Comment by semioticrobotic** [comment]
We've merged #22, which sets the stage for more of this work, and will update this issue when the Open Leadership Definition is finalized and typeset.

**Comment by semioticrobotic** [comment]
I realize this is finished! Closing now.
