### ISSUE TITLE
Open external links in a new tab/window

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-organization.github.io#4]
I suggest that links that points to another site would open in a new tab or window as you are leaving the main site and its menu navigation.

**Comment by semioticrobotic** [comment]
Thanks, @jimmysjolund. I tried to address this with [a recent code push](https://github.com/open-organization/open-organization.github.io/commit/b80d0fc7dbf46f248c3b3c67952ad7752c1f390c). Does that address the issue the way you're imagining?

**Comment by trncb** [comment]
@jimmysjolund are you suggesting for every external link in the website or just the navigation? 

If this is for every link, this is not a standard feature in Markdown and therefore could add a little more complexity. For example, instead of using `[example](http://example.com)` to add a link to a page, one would need to remember to use the full HTML href code `<a href="http://example.com/" target="_blank">example</a>` when an external link is added.

There seems to be no standard on this around the web and I guess it comes down to a project decision.

**Comment by jimmysjolund** [comment]
Yes, I propose that all external links open in a new window/tab as you otherwise lose your navigation when clicking a link that end up in another site. In the CMS' I've worked with this is usually a global setting or a plugin switch. Not something you do for every link manually.

**Comment by semioticrobotic** [comment]
Thanks very much for this discussion, @trncb and @jimmysjolund. I definitely see the usability value @jimmysjolund proposes here, though I agree with @trncb that it adds an unfortunate (albeit relatively small) step in the site coding process. If we believe the tradeoff is worth making, though, I don't mind adopting this convention site-wide (as opposed to only in menus, as it is currently).

**Comment by LauraHilliger** [comment]
ahhh yee ol' external links and target blank conversation – one of the old school arguments of the web! Most usability folks would say that site visitors know how to open a link in a new window or tab. Given that we'd have to fiddle to make this happen, I'd vote for the main navigation external links (e.g. "Articles" and "Community") opening in a new tab/window and leaving everything else alone. Here's a nice article  on the debate: https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187

**Comment by semioticrobotic** [comment]
Thanks, @LauraHilliger. I prefer to maintain standards when possible (and it seems like @trncb does too), so let's just limit this behavior to the menu for now.
